# Generated by Django 4.2.7 on 2023-12-31 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified_key',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Ключ верификации'),
        ),
    ]
